CONFIG_ZMK_BLE=n
CONFIG_ZMK_BLE_EXPERIMENTAL_CONN=n
CONFIG_ZMK_SPLIT_BLE=n
CONFIG_ZMK_SPLIT_WIRED=n
CONFIG_ZMK_SPLIT_ESB=y
CONFIG_ESB_MAX_PAYLOAD_LENGTH=48

CONFIG_ZMK_BATTERY_REPORTING=y
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_FETCHING=y
CONFIG_ZMK_SPLIT_BLE_CENTRAL_BATTERY_LEVEL_PROXY=y

CONFIG_ZMK_SLEEP=n

# USB Logging
CONFIG_ZMK_USB_LOGGING=y
# CONFIG_LOG_MODE_IMMEDIATE=n
# CONFIG_LOG_TIMESTAMP_64BIT=y
# CONFIG_LOG_PROCESS_THREAD_STARTUP_DELAY_MS=5000
# CONFIG_ZMK_LOG_LEVEL_DBG=y
# CONFIG_KSCAN_LOG_LEVEL_INF=y
