manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: caksoylar
      url-base: https://github.com/caksoylar
    - name: badjeff
      url-base: https://github.com/badjeff/
    - name: efogdev
      url-base: https://github.com/efogdev
    - name: nuovotaka
      url-base: https://github.com/nuovotaka
  projects:
    - name: zmk
      remote: zmkfirmware
      # main @ 2026-08-11 - both local patches were generated against this tree
      revision: 6e2ef41e022d555b10f116e395832913f71717b3
      import: app/west.yml
    - name: zmk-rgbled-widget
      remote: caksoylar
      # main @ 2026-07-09
      revision: e6b467792a1dabef8cfa5c9fd26bfefc9c16662b
    - name: zmk-pmw3610-driver
      remote: efogdev
      # zephyr-4.1 @ 2026-04-17
      revision: 38105b4f09d6d5b94ef5a3073428719e3c356af1
    - name: zmk-input-processor-report-rate-limit
      remote: badjeff
      # main @ 2026-03-08
      revision: b056cb135525933743e2627150fb390f9d4b2461
    - name: zmk-behavior-battery-percentage-printer
      remote: badjeff
      # main @ 2025-11-17
      revision: e111cbc6ac66caaa157daeb58eda3c8e2b43153a
    - name: zmk-pointing-acceleration-alpha
      remote: nuovotaka
      # main @ 2025-09-09 - alpha module, governs pointer acceleration
      revision: 780dfcd6b796063367893ff41e233773e12fb07c
  self:
    path: config
