manifest:
  remotes:
    - name: zmkfirmware
      url-base: https://github.com/zmkfirmware
    - name: heavydutysoul
      url-base: https://github.com/HeavyDutySoul
  projects:
    - name: zmk
      remote: heavydutysoul
      revision: feat/battery-reporting
      import: app/west.yml
  self:
    path: config